---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-storage
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  interval: 10m
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-storage
  namespace: nfs-storage
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "4.0.x"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
  interval: 10m
  releaseName: nfs-subdir-external-provisioner
  targetNamespace: nfs-storage
  values:
    storageClass:
      name: nfs-storage
    nfs:
      path: /mnt/data/@k8s
      server: 192.168.0.10

