apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer

spec:
  values:
    $patch: add
    persistance:
      storageClass: longhorn
    
    ingress:
      enabled: true
      hosts:
        - host: sks.solufit.net
          paths:
            - /portainer/
      annotations:
        kubernetes.io/ingress.class: one-traefik
