---
apiVersion: v1
kind: Namespace
metadata:
  name: portainer
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: portainer
  namespace: flux-system
spec:
  interval: 10m
  url: https://portainer.github.io/k8s/

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  chart:
    spec:
      chart: portainer
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: flux-system
  interval: 10m
  releaseName: portainer
  targetNamespace: portainer
  values:
    persistence:
      storageClass: nfs-storage
    service:
      type: LoadBalancer
