apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  values:
    ingress:
      enabled: true
      hosts:
        - host: sks.solufit.net
          paths:
            - /flux/
      annotations:
        kubernetes.io/ingress.class: one-traefik