---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cloudflare
  namespace: flux-system
spec:
  interval: 60m0s
  url: https://cloudflare.github.io/helm-charts
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  chart:
    spec:
      chart: cloudflare-tunnel-remote
      version: "0.1.x"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
  interval: 10m
  releaseName: cloudflare-tunnel-remote
  targetNamespace: cloudflared

