---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 60m0s
  url: https://grafana.github.io/helm-charts
---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitor
spec:
  chart:
    spec:
      chart: grafana
      version: "7.3.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    service:
      type: ClusterIP
    adminUser: admin
    adminPassword: secret
  interval: 10m
  releaseName: grafana
  targetNamespace: monitor