apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./metrics-server.yaml"
  - "./eso.yaml"
  - "./kube-prometheus-stack.yaml"
  - "./loki-stack.yaml"
  - "./cloudflared.yaml"
  - "./weave-gitops.yaml"
  - "./portainer.yaml"

