---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 60m0s
  url: https://grafana.github.io/helm-charts
---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitor
spec:
  chart:
    spec:
      chart: loki-stack
      version: "2.9.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    fluent:
      enable: true
    promtail:
      enable: true
  interval: 10m
  releaseName: loki-stack
  targetNamespace: monitor