apiVersion: v1
kind: Namespace
metadata:
  name: metrics
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics
spec:
  chart:
    spec:
      chart: metrics-server
      version: "7.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  releaseName: metrics-server
  targetNamespace: metrics
  interval: 5m