apiVersion: v1
kind: Namespace
metadata:
  name: metrics-collector
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 10m
  url: https://kubernetes-sigs.github.io/metrics-server/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-collector
spec:
  chart:
    spec:
      chart: metrics-server
      version: "3.12.x"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  releaseName: metrics-server
  targetNamespace: metrics-collector
  interval: 5m