apiVersion: v1
kind: Namespace
metadata:
  name: monitor

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  chart:
    spec:
      chart: prometheus
      version: "25.x.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 10m
  releaseName: prometheus
  targetNamespace: monitor
  values:
    server.persistentVolume.enabled: false

