apiVersion: v1
kind: Namespace
metadata:
  name: monitor
  labels:
    toolkit.fluxcd.io/tenant: sre-team

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitor
spec:
  chart:
    spec:
      chart: prometheus
      version: "25.x.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 10m
  releaseName: prometheus
  targetNamespace: monitor
  values:
    server.persistentVolume.enabled: false


---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitor
spec:
  chart:
    spec:
      chart: grafana
      version: "7.3.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 10m
  releaseName: grafana
  targetNamespace: monitor
  values:
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            orgId: 1
            url: http://prometheus.monitor.svc.cluster.local
            isDefault: true