apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0"
#  values:
#    ingress:
#      enabled: true
#      annotations:
#        external-dns.alpha.kubernetes.io/hostname: lapis-dev.f5.si
#        cert-manager.io/cluster-issuer: letsencrypt
#        kubernetes.io/ingress.class: nginx
#        acme.cert-manager.io/http01-edit-in-place: "true"
#      hosts:
#        - host: lapis-dev.f5.si
#          paths:
#            - path: /
#              pathType: ImplementationSpecific
#
#      tls:
#        - secretName: letsencrypt-podinfo-cert
#          hosts:
#            - lapis-dev.f5.si
#
#